import random
import asyncio
import uuid
import shutil
import os
from datetime import datetime, timedelta
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.interval import IntervalTrigger
from sqlmodel import Session
from app.db import engine
from app.models import Post
from app.ai.multi_reply import generate_multi_replies

scheduler = AsyncIOScheduler()

async def daily_thread_job():
    """
    Daily automatic thread creation by system AI.
    """
    lang = "jp" # Default JP
    
    # Generate Topic (Standardized to English to avoid encoding issues)
    topics = [
        "Recent AI progress is fast, isn't it?",
        "What programming language should I learn first?",
        "Remote work pros and cons",
        "Dinner recommendations?",
        "Engineer survival strategies",
        "Vue vs React vs Angular",
        "Questions from a newbie engineer",
        "My favorite VTuber is cute",
        "Deployment failed... help",
        "Git rebase is scary"
    ]
    topic = random.choice(topics)
    
    with Session(engine) as session:
        # Create Thread (Root Post)
        gen_id = str(uuid.uuid4())
        
        # Name: "Anonymous" or "Nanashi" in JP
        name = "名無しさん" if lang == "jp" else "Anonymous"
        
        root = Post(
            language=lang,
            name=name,
            content=topic,
            is_ai=True, # Generated by system but acts as user
            persona="System",
            thread_id=None, # Will set to ID
            gen_id=gen_id,
            depth=0
        )
        session.add(root)
        session.commit()
        session.refresh(root)
        
        root.thread_id = root.id
        session.add(root)
        session.commit()
        
        print(f"[Scheduler] Created thread #{root.id}: {topic}")

        # Initial AI Replies (Self-acting)
        replies = generate_multi_replies(topic, lang=lang, context=f"Title: {topic}")
        
        for r in replies:
            ai_post = Post(
                language=lang,
                name=r["name"],
                persona=r["name"],
                content=r["content"],
                is_ai=True,
                reply_to_id=root.id,
                thread_id=root.id,
                gen_id=gen_id,
                depth=1
            )
            session.add(ai_post)
        
        session.commit()
        print(f"[Scheduler] Added {len(replies)} replies to thread #{root.id}")


def daily_db_backup_job():
    """
    Daily SQLite Backup. Keep last 7 days.
    """
    db_file = "bbs_v2.sqlite3"
    backup_dir = "backups"
    if not os.path.exists(backup_dir):
        os.makedirs(backup_dir)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = os.path.join(backup_dir, f"bbs_v2_{timestamp}.sqlite3")
    
    # Simple copy
    if os.path.exists(db_file):
        shutil.copy2(db_file, backup_path)
        print(f"[Backup] Saved to {backup_path}")
    
    # Cleanup old
    files = sorted([os.path.join(backup_dir, f) for f in os.listdir(backup_dir) if f.startswith("bbs_v2_")])
    if len(files) > 7:
        for f in files[:-7]:
            os.remove(f)
            print(f"[Backup] Removed old: {f}")

def start_scheduler():
    # Run 5 times a day? 
    # For MVP simplicity: Interval every 4 hours approx.
    
    # Add job
    scheduler.add_job(daily_thread_job, IntervalTrigger(hours=4))
    
    # Backup Job (Every day at 03:15)
    scheduler.add_job(daily_db_backup_job, 'cron', hour=3, minute=15)
    
    scheduler.start()
    print("[Scheduler] Started.")
